### ISSUE TITLE
I use your example. How to fix this?

### ISSUE THREAD

**Issue by Rstacx** [aiko-chan-ai/Discord-video-selfbot#12]
I use your example. How to fix this?
```
/root/live-bot/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:265
        throw new Error(WSCodes[error.code]);
              ^
Error [INVALID_INTENTS]: [Bot Token] Invalid intent provided for WebSocket intents.
    at WebSocketManager.createShards (/root/live-bot/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:265:15)
    at async Client.login (/root/live-bot/node_modules/discord.js-selfbot-v13/src/client/Client.js:344:7) {
  [Symbol(code)]: 'INVALID_INTENTS'
}
```

**Comment by aiko-chan-ai** [comment]
Pls use user token
